#!/bin/bash

DIR="$HOME/.config/sketchybar/"
ITEM_DIR="$DIR/items"
PLUGIN_DIR="$DIR/plugins"

FONT="JetBrainsMono Nerd Font"
ICON_FONT="SF Pro"

PADDING=6

source "$DIR/colors.sh"
source "$DIR/icons.sh"

BAR_PROPS=(
  height=50
  color=$BG_PRI_COLR
  shadow=off
  position=bottom
  sticky=on
  padding_right=15
  padding_left=15
  corner_radius=0
  y_offset=0
  margin=0
  blur_radius=30
  notch_width=0
)

DEF_PROPS=(
  updates=when_shown
  icon.font="$ICON_FONT:Regular:20.0"
  icon.color=$WHITE
  icon.padding_left=10
  icon.padding_right=2
  label.font="$FONT:Bold:18.0"
  label.color=$WHITE
  label.padding_left=$PADDING
  label.padding_right=10
  background.color=$BG_PRI_COLOR
  background.padding_right=$PADDING
  background.padding_left=$PADDING
  background.height=30
  background.corner_radius=7
)

sketchybar --bar "${BAR_PROPS[@]}"
sketchybar --default "${DEF_PROPS[@]}"

# -- LEFT Side Items --
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# -- RIGHT Side Items -- 
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/cpu.sh"
source $ITEM_DIR/vpn.sh
# sketchybar --add item cat center \
#            --set cat icon="≽^•⩊•^≼"\
#                      icon.font="$ICON_FONT:Regular:18.0" \
#                      icon.color=$DARK_WHITE\
#                      label.draw=off
#
#
sketchybar --update

