
format = """
[$directory](bold blue)($git_branch$git_state$git_status$git_metrics$nodejs$rust$golang$php$c$python$kotlin$java$zig)
$time $hostname $username [»](bold blue) """

[git_branch]
style = "bold blue"
format = "[\\[[$symbol$branch$tag](bold blue)\\]](bold white)"
symbol = "\ue725 "

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style))'

[directory]
style = "bold blue"
truncate_to_repo = false
# truncation_length = 1
 fish_style_pwd_dir_length = 1


[golang]
format = "([( $symbol ($version) )]($style))"
style = "bg:#24283b bold fg:#7dcfff"
symbol = "󰟓"

[java]
format = "([( $symbol ($version) )]($style))"
style = "bg:#24283b bold fg:#ff9e64"
symbol = ""

[kotlin]
format = "([( $symbol ($version) )]($style))"
style = "bg:#24283b bold fg:#bb9af7"
symbol = ""

[nix_shell]
format = "$state"
impure_msg = "[  Impure ](bg:#272d40 bold fg:#bb9af7)"
pure_msg = "[  Pure ](bg:#272d40 bold fg:#769ff0)"

[nodejs]
format = "([( $symbol ($version) )]($style))"
style = "bg:#24283b bold fg:#7BD88F"
symbol = ""

[php]
format = "([( $symbol ($version) )]($style))"
style = "bg:#24283b bold fg:#769ff0"
symbol = ""

[python]
format = "([( $symbol ($version) )]($style))"
style = "bg:#24283b bold fg:#7bd88f"
symbol = "󰌠"

[rust]
format = "([( $symbol ($version) )]($style))"
style = "bg:#24283b bold fg:#FF9E64"
symbol = ""

[zig]
format = "([( $symbol ($version) )]($style))"
style = "bg:#24283b bold fg:#ff9e64"
symbol = ""


[username]
show_always = true
style_user = "bold white"
format = "[$user]($style)"

[time]
disabled = false
style = "bold blue"
format = "[$time]($style)"
time_format = "%H:%M"

