format = """
[$directory](bold cyan)($git_branch$git_state$git_status$git_metrics)
$time $hostname $username $python[»](bold green) """

[git_branch]
style = "bold green"
format = "[\\[[$symbol$branch$tag](bold green)\\]](bold white)"
symbol = "\ue725 "

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style))'

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1

[python]
disabled = false
pyenv_version_name = false
python_binary = 'python'
format = '[${symbol}(\($virtualenv\))]($style)'
style = "fg:#a48989"
symbol = "• 󱔎 "


[java]
disabled = false
symbol = "•  "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[lua]
disabled = false
symbol = "•  "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[nodejs]
disabled = false
symbol = "• 󰎙 "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[package]
disabled = false
symbol = "•  "
display_private = false
format = '[${symbol}]($style)'
style = "fg:#a48989"

[docker_context]
disabled = false
symbol = "•  "
only_with_files = true
format = '[${symbol}]($style)'
style = "fg:#a48989"

[rust]
disabled = false
symbol = "• 󰰠 "
format = '[${symbol}]($style)'
style = "fg:#a48989"
[ruby]
disabled = true

[swift]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold white"

[username]
show_always = true
style_user = "bold white"
format = "[$user]($style)"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"
